<?php

namespace Tests\Integration\Views;

use App\Models\FrontUser;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Lang;
use Laravel\Socialite\One\User;
use Tests\TestCase;

class AdminRecipientControllerTest extends TestCase
{
    protected \App\Models\User $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::beginTransaction();

        $this->user = FrontUser::factory()->create(['isAdmin' => true]) ?? new FrontUser();
    }

    public function test_content(): void
    {
        auth()->login($this->user);

        $this
            ->get(route('adminRecipient.show'))
            ->assertSeeText(Lang::get('recipientMessages.pageTitle'))
            ->assertSee(Lang::get('recipientMessages.storeRecipientButton'));
    }

    protected function tearDown(): void
    {
        DB::rollBack();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
