<?php

namespace Tests\Integration\Middleware;

use App\Http\Middleware\VerifyCsrfToken;
use App\Models\Category;
use App\Models\FrontCategory;
use App\Models\FrontProduct;
use App\Models\FrontUser;
use App\Models\User;
use Faker\Factory;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class HomeControllerTest extends TestCase
{
    protected User $user;

    protected Category $category;

    protected function setUp(): void
    {
        parent::setUp();
        Factory::create();
        $this->withoutMiddleware(VerifyCsrfToken::class);

        DB::beginTransaction();

        $this->user = FrontUser::factory()->create(['isAdmin' => false]) ?? new FrontUser();
    }

    public function test_home_page_unauthorized_access(): void
    {
        $this->get(route('home.index'))->assertStatus(200);
    }

    public function test_home_page_authorized_access(): void
    {
        auth()->login($this->user);
        $this->get(route('home.index'))->assertStatus(200);
    }

    protected function tearDown(): void
    {
        DB::rollBack();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}
