<?php

namespace Tests\Integration\Middleware;

use App\Http\Middleware\VerifyCsrfToken;
use App\Models\Category;
use App\Models\FrontCategory;
use App\Models\FrontProduct;
use App\Models\FrontUser;
use App\Models\User;
use Faker\Factory;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class OrderControllerTest extends TestCase
{
    protected User $user;

    protected Category $category;

    protected function setUp(): void
    {
        parent::setUp();
        Factory::create();
        $this->withoutMiddleware(VerifyCsrfToken::class);

        DB::beginTransaction();

        $this->user = FrontUser::factory()->create(['isAdmin' => false]) ?? new FrontUser();
    }

    public function test_unauthorized_store(): void
    {
        $this->post(route('order.store', ['product' => -1]))->assertRedirect();
    }

    public function test_unauthorized_index(): void
    {
        $this->get(route('order.index'))->assertRedirect();
    }

    public function test_unauthorized_delete(): void
    {
        $this->post(route('order.destroy', ['order' => -1]))->assertRedirect();
    }

    protected function tearDown(): void
    {
        DB::rollBack();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}
