<?php

namespace Tests\Integration\Models;

use App\Models\Category;
use App\Models\FrontCategory;
use App\Models\FrontUser;
use App\Models\Order;
use App\Models\FrontProduct;
use App\Models\Product;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class  ProductTest extends TestCase
{


    private Category $category;

    private Product $product;

    private User $user;

    private Order $order;

    protected $faker;


    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::beginTransaction();
        $this->category = FrontCategory::factory()->create() ?? new FrontCategory();

        $this->product = self::createProduct($this->category->getAttribute('id'));
        $this->product->save();

        $this->user = FrontUser::factory()->create(['isAdmin' => false]) ?? new FrontUser();

        $this->order = self::creatreOrder($this->user->getAttribute('id'), $this->product->getId());
        $this->order->save();

    }

    public function test_get_category_id(): void
    {
        $this->assertEquals($this->product->getCategoryId(), $this->category->getAttribute('id'));
    }

    public function test_product_orders(): void
    {
        $this->assertEquals($this->product->orders()->first()->getAttribute('productId'), $this->product->getId());
    }

    protected function tearDown(): void
    {
        DB::rollBack();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
