<?php

namespace Tests\Integration\Models;

use App\Http\Middleware\VerifyCsrfToken;
use App\Models\FrontCategory;
use App\Models\Order;
use App\Models\OrderRecipientRole;
use App\Models\FrontProduct;
use App\Models\Recipient;
use App\Models\Role;
use App\Models\FrontUser;
use Faker\Factory;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class  RecipientTest extends TestCase
{
    private Recipient $recipient;

    private Role $role;


    protected $faker;


    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::beginTransaction();

        $this->faker = Factory::create();

        $this->role = new Role(
            [
                'name' => $this->faker->text(self::STR_LEN_FOR_TESTS),
                'type' => OrderRecipientRole::getType()
            ]
        );
        $this->role->save();

        $this->recipient = self::createRecipient($this->role->getAttribute('id'));
        $this->recipient->save();
    }

    public function test_role_relation(): void
    {
        $this->assertEquals(
            $this->recipient->role()->first()->getAttribute('name'),
            $this->role->getAttribute('name')
        );
    }

    protected function tearDown(): void
    {
        DB::rollBack();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
