<?php

namespace Tests\Integration\Controllers;

use App\Http\Middleware\VerifyCsrfToken;
use App\Models\FrontCategory;
use App\Models\FrontProduct;
use App\Models\FrontUser;
use App\Models\User;
use Faker\Factory;
use Illuminate\Support\Facades\DB;


class AdminProductShowTest extends \Tests\TestCase
{
    protected User $user;

    protected function setUp(): void
    {
        parent::setUp();
        $this->withoutMiddleware(VerifyCsrfToken::class);
        DB::beginTransaction();

        $this->user = FrontUser::factory()->create(['isAdmin' => true]) ?? new FrontUser();

        auth()->login($this->user);
    }

    public function test_show(): void
    {
        $this->get(route('adminProduct.show'))->assertStatus(200);
    }

    protected function tearDown(): void
    {
        DB::rollBack();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}
