<?php

namespace Tests\Integration\Controllers;

use App\Http\Controllers\ProductController;
use App\Http\Middleware\VerifyCsrfToken;
use App\Models\Category;
use App\Models\FrontCategory;
use App\Models\FrontProduct;
use App\Models\FrontUser;
use App\Models\Product;
use App\Models\User;
use Faker\Factory;
use Illuminate\Support\Facades\DB;


class ProductShowControllerTest extends \Tests\TestCase
{
    protected $faker;

    protected Product $product;

    protected User $user;

    protected function setUp(): void
    {
        parent::setUp();
        $this->faker = Factory::create();
        DB::beginTransaction();

        $this->product = FrontProduct::factory()->create() ?? new FrontProduct();
        $this->user = FrontUser::factory()->create(['isAdmin' => true]) ?? new FrontUser();
    }

    /**
     * Assert, that there will be data with product in show product page
     */
    public function test_edit(): void
    {
       $response = $this->get(route('product.show', ['product' => $this->product->getAttribute('id')]));
       $response->assertSee($this->product->getName());
    }

    protected function tearDown(): void
    {
        auth()->logout();
        DB::rollBack();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}
